"""Attribute name constants for TraceCtrl span schema."""

# Standard OpenInference fields
OI_SPAN_KIND = "openinference.span.kind"
INPUT_VALUE = "input.value"
OUTPUT_VALUE = "output.value"
LLM_MODEL_NAME = "llm.model_name"
LLM_SYSTEM = "llm.system"
LLM_PROMPT_TEMPLATE = "llm.prompt_template.template"
TOOL_NAME = "tool.name"
TOOL_DESCRIPTION = "tool.description"
TOOL_PARAMETERS = "tool.parameters"
RETRIEVAL_DOCUMENTS = "retrieval.documents"

# TraceCtrl security fields
TC_AGENT_ID = "tracectrl.agent.id"
TC_AGENT_NAME = "tracectrl.agent.name"
TC_AGENT_ROLE = "tracectrl.agent.role"
TC_AGENT_FRAMEWORK = "tracectrl.agent.framework"
TC_SESSION_ID = "tracectrl.session_id"
TC_CALLER_AGENT_ID = "tracectrl.caller.agent_id"
TC_INPUT_SOURCE = "tracectrl.input.source"
TC_TOOL_CATEGORY = "tracectrl.tool.category"
TC_TOOL_TARGET = "tracectrl.tool.target"
TC_MEMORY_OPERATION = "tracectrl.memory.operation"
TC_MEMORY_STORE_ID = "tracectrl.memory.store_id"
TC_MEMORY_WRITE_PROVENANCE = "tracectrl.memory.write_provenance"
TC_SYSTEM_PROMPT_HASH = "tracectrl.system_prompt_hash"
TC_SPAN_SEQUENCE = "tracectrl.span_sequence"
